// ======================================================
// PHASE 9D — Worker physical extraction guards
// ======================================================
// Phase 9D made the worker a self-contained standalone package/artifact:
//
//   - the runtime bundle stays at worker/worker/ (the physical location
//     every deployment channel already consumes: hub volume mount, install
//     manifests, installer repo-checkout fallback — moving it would break
//     deployment for zero runtime benefit);
//   - blocker B2 resolved via option B: the bundle carries an EXPLICITLY
//     GENERATED byte-exact copy of the canonical Job Protocol v2
//     implementation (@animastor/contracts) instead of a second, silently
//     maintained inline copy;
//   - package-owned unit tests moved into worker/tests/ (zero-dep harness);
//   - the package is standalone: `node worker.cjs` from a clean copy, no
//     monorepo code reach-ins, no npm registry needed.
//
// Guards in this suite:
//   D1  package manifest: name/version/private/zero-deps/engines
//   D2  bundle surface freeze (hub tar ships everything except .env*)
//   D3  require containment: only builtins + files INSIDE the bundle
//       (no requires reaching into backend/, gpu-hub/, frontends/…)
//   D4  generated protocol copy: byte parity with the canonical contracts
//       source + header version/sha256 stamps (sync: worker/tools/sync-protocol.cjs)
//   D5  worker.cjs consumes the generated copy (no second inline implementation)
//   D6  install manifests ship the full runtime set incl. the generated copy
//   D7  deployment wiring unchanged (hub volume mounts stay on worker/worker/)
//   D8  negative control: the parity guard detects a diverged copy
//
// Docs: docs/architecture/PHASE_9D_WORKER_PHYSICAL_EXTRACTION_AUDIT.md

const { expect } = require('chai');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const crypto = require('crypto');
const { REPO_ROOT, listSourceFiles, readSource, rel, requireSpecifiers } = require('./helpers');

const BUNDLE_DIR = path.join(REPO_ROOT, 'worker', 'worker');
const WORKER_TESTS_DIR = path.join(REPO_ROOT, 'worker', 'tests');
const SYNC_TOOL_PATH = path.join(REPO_ROOT, 'worker', 'tools', 'sync-protocol.cjs');
const CONTRACTS_IMPL_PATH = path.join(REPO_ROOT, 'contracts', 'src', 'job-protocol-v2.js');
const MANIFEST_ROOT = path.join(REPO_ROOT, 'backend', 'ai', 'install-manifests');

const RUNTIME_FILES = [
    'worker.cjs',
    'worker-env.cjs',
    'worker-cleanup.cjs',
    'worker-cleanup-journal.cjs',
    'job-protocol-v2.cjs',
    'package.json',
    'package-lock.json',
    '.env.example',
].sort();

function sha256(buf) {
    return crypto.createHash('sha256').update(buf).digest('hex');
}

// ── D1 — package manifest ────────────────────────────────────────────────
describe('Phase 9D: worker package manifest', () => {
    it('stands alone: canonical version, private, zero runtime deps, engines pinned', () => {
        const pkg = JSON.parse(fs.readFileSync(path.join(BUNDLE_DIR, 'package.json'), 'utf8'));
        expect(pkg.name).to.equal('animastor-worker');
        expect(pkg.version).to.match(/^\d+\.\d+\.\d+$/);
        expect(pkg.version).to.equal('2.1.0');
        expect(pkg.private, 'the package must be publishable to an npm registry').to.not.equal(true);
        expect(pkg.dependencies, 'zero runtime npm dependencies (Phase 9B freeze)').to.not.exist;
        expect(pkg.optionalDependencies).to.not.exist;
        expect(pkg.devDependencies, 'the bundle must stay install-free (dev tests live outside via zero-dep harness)').to.not.exist;
        expect(pkg.engines && pkg.engines.node).to.be.a('string');
        expect(pkg.main).to.equal('worker.cjs');
    });
});

// ── D2 — bundle surface freeze ───────────────────────────────────────────
describe('Phase 9D: bundle surface freeze', () => {
    it('worker/worker/ contains exactly the runtime set (tests live one level up)', () => {
        const entries = fs.readdirSync(BUNDLE_DIR).sort();
        expect(entries, 'unexpected files would ship in the hub bundle tar (walkDir takes everything except .env*)').to.deep.equal(RUNTIME_FILES);
        // Package-owned tests sit at worker/tests/ — inside the package
        // boundary but OUTSIDE the bundle dir, so they never ship in the
        // hub tar and never enter npm pack (package.json "files" allowlist).
        expect(fs.existsSync(WORKER_TESTS_DIR), 'package-owned tests must exist at worker/tests/').to.equal(true);
        expect(fs.existsSync(path.join(BUNDLE_DIR, 'tests')), 'no tests/ inside the bundle dir itself').to.equal(false);
    });

    it('package-owned tests are zero-dependency and self-contained (standalone smoke)', () => {
        const builtins = new Set(require('module').builtinModules);
        const offenders = [];
        for (const file of listSourceFiles(WORKER_TESTS_DIR)) {
            for (const spec of requireSpecifiers(readSource(file))) {
                if (spec.startsWith('.')) continue;
                if (builtins.has(spec)) continue;
                offenders.push(`${rel(file)}: ${spec}`);
            }
        }
        expect(offenders, 'package tests must run without npm install (zero-dep harness)').to.deep.equal([]);
    });
});

// ── D3 — require containment (no monorepo reach-ins) ─────────────────────
describe('Phase 9D: bundle require containment', () => {
    it('all relative requires resolve INSIDE the worker package boundary', () => {
        const offenders = [];
        for (const file of listSourceFiles(BUNDLE_DIR)) {
            for (const spec of requireSpecifiers(readSource(file))) {
                if (!spec.startsWith('.')) continue;
                const resolved = path.resolve(path.dirname(file), spec);
                if (!resolved.startsWith(BUNDLE_DIR + path.sep)) {
                    offenders.push(`${rel(file)}: ${spec}`);
                }
            }
        }
        expect(offenders, 'worker runtime must never require outside its package boundary').to.deep.equal([]);
    });

    it('no monorepo path fragments in bundle require specifiers', () => {
        const banned = /backend\/|gpu-hub\/|frontends\/|contracts\/|ai-connector\//;
        const offenders = [];
        for (const file of listSourceFiles(BUNDLE_DIR)) {
            for (const spec of requireSpecifiers(readSource(file))) {
                if (banned.test(spec)) offenders.push(`${rel(file)}: ${spec}`);
            }
        }
        expect(offenders, 'monorepo-relative paths must not leak into the standalone bundle').to.deep.equal([]);
    });

    it('negative control: a monorepo reach-in is detected', function () {
        this.timeout(5000);
        const offenderPath = path.join(BUNDLE_DIR, '__guard_negative_control__.cjs');
        let detected;
        try {
            fs.writeFileSync(offenderPath, "// synthetic violation\nconst x = require('../../backend/src/runtime/job-schema.js');\nmodule.exports = { x };\n");
            detected = [];
            for (const spec of requireSpecifiers(readSource(offenderPath))) {
                if (!spec.startsWith('.')) continue;
                const resolved = path.resolve(BUNDLE_DIR, spec);
                if (!resolved.startsWith(BUNDLE_DIR + path.sep)) detected.push(spec);
            }
        } finally {
            if (fs.existsSync(offenderPath)) fs.rmSync(offenderPath, { force: true });
        }
        expect(detected).to.deep.equal(['../../backend/src/runtime/job-schema.js']);
    });
});

// ── D4 — generated protocol copy parity ──────────────────────────────────
describe('Phase 9D: generated Job Protocol v2 copy (blocker B2, option B)', () => {
    const syncTool = require(SYNC_TOOL_PATH);

    it('the generator exists and the copy is byte-parity in sync with @animastor/contracts', () => {
        expect(fs.existsSync(SYNC_TOOL_PATH), 'worker/tools/sync-protocol.cjs must exist').to.equal(true);
        const res = syncTool.verify();
        expect(res.ok, `generated copy drift: ${res.errors.join('; ')}`).to.equal(true);
    });

    it('the copy carries the GENERATED header with canonical sha256 + contracts version stamps', () => {
        const copy = fs.readFileSync(syncTool.BUNDLE_TARGET, 'utf8');
        const canonical = fs.readFileSync(CONTRACTS_IMPL_PATH, 'utf8');
        expect(copy).to.include('GENERATED FILE — DO NOT EDIT BY HAND');
        expect(copy).to.include('@animastor/contracts');
        expect(copy).to.include(`sha256:    ${sha256(canonical)}`);
        // header declares provenance (generator path), not an invented source
        expect(copy).to.include('worker/tools/sync-protocol.cjs');
    });

    it('regeneration is deterministic and idempotent (no diffs on re-run)', function () {
        this.timeout(10000);
        const before = fs.readFileSync(syncTool.BUNDLE_TARGET, 'utf8');
        const res = syncTool.verify();
        expect(res.ok).to.equal(true);
        // re-run the generator through its CLI (--check verifies only) and
        // then regenerate in place via the module API; bytes must not change
        execFileSync(process.execPath, [SYNC_TOOL_PATH], { cwd: REPO_ROOT });
        const after = fs.readFileSync(syncTool.BUNDLE_TARGET, 'utf8');
        expect(after).to.equal(before);
    });
});

// ── D5 — worker.cjs consumes the copy (no second implementation) ─────────
describe('Phase 9D: worker runtime consumes the generated copy', () => {
    it('worker.cjs requires the copy and defines no local protocol literals', () => {
        const worker = readSource(path.join(BUNDLE_DIR, 'worker.cjs'));
        expect(worker).to.include('require("./job-protocol-v2.cjs")');
        expect(worker, 'PROTOCOL_VERSION must come from the generated copy').to.not.match(/PROTOCOL_VERSION\s*=\s*\d/);
        expect(worker, 'split regex must come from the generated copy').to.not.include('/:(iu_image|image|audio|video)$/');
        expect(worker.match(/job_id\.split\(JOB_ID_SPLIT_RE\)/g), 'exactly two split call sites').to.have.lengthOf(2);
    });

    it('worker package tests pin the same contour (protocol + package suites registered)', () => {
        const runner = fs.readFileSync(path.join(WORKER_TESTS_DIR, 'run-all.cjs'), 'utf8');
        for (const suite of ['job-protocol.test.cjs', 'package.test.cjs', 'worker-env.test.cjs', 'worker-cleanup.test.cjs', 'worker-cleanup-journal.test.cjs']) {
            expect(runner).to.include(suite);
        }
    });
});

// ── D6 — install manifests ship the full runtime set ─────────────────────
describe('Phase 9D: install manifests ship the runtime set', () => {
    it('every manifest lists the exact runtime file set (incl. the generated copy)', () => {
        for (const type of fs.readdirSync(MANIFEST_ROOT).sort()) {
            const typeDir = path.join(MANIFEST_ROOT, type);
            if (!fs.statSync(typeDir).isDirectory()) continue;
            for (const file of fs.readdirSync(typeDir).sort()) {
                if (!file.endsWith('.json')) continue;
                const m = JSON.parse(fs.readFileSync(path.join(typeDir, file), 'utf8'));
                expect(m.worker_bundle.files.sort(), `${type}/${file}`).to.deep.equal(RUNTIME_FILES);
                expect(m.worker_bundle.source.options.map((o) => o.path), `${type}/${file} repo path`)
                    .to.include('worker/worker/');
            }
        }
    });
});

// ── D7 — deployment wiring unchanged (compat channels stay on the path) ──
describe('Phase 9D: deployment wiring unchanged', () => {
    it('hub volume mounts stay pinned to worker/worker/ (rollback-safe extraction)', () => {
        const compose = fs.readFileSync(path.join(REPO_ROOT, 'docker-compose.yml'), 'utf8');
        expect(compose).to.include('./worker/worker/worker.cjs:/app/worker-source/worker.cjs:ro');
        expect(compose).to.include('./worker/worker:/app/worker-bundle:ro');
    });
});

// ── D8 — negative control: parity guard catches divergence ───────────────
describe('Phase 9D: negative control — parity guard catches divergence', () => {
    it('a tampered copy body is rejected by the sync tool verification', () => {
        const syncTool = require(SYNC_TOOL_PATH);
        const canonical = fs.readFileSync(CONTRACTS_IMPL_PATH, 'utf8');
        const target = syncTool.BUNDLE_TARGET;
        const original = fs.readFileSync(target, 'utf8');
        try {
            // simulate manual divergence: flip a wire constant in the copy
            const tampered = original.replace('const PROTOCOL_VERSION = 2;', 'const PROTOCOL_VERSION = 3;');
            expect(tampered).to.not.equal(original, 'tamper must change the file for the control to be meaningful');
            fs.writeFileSync(target, tampered);
            const res = syncTool.verify();
            expect(res.ok, 'parity guard must catch a diverged copy').to.equal(false);
            expect(res.errors.join('\n')).to.match(/diverges from the canonical source|PROTOCOL_VERSION drift/);
        } finally {
            fs.writeFileSync(target, original);
        }
        expect(syncTool.verify().ok, 'restore must bring the copy back in sync').to.equal(true);
    });
});
